<?php
declare(strict_types=1);

namespace Vodacom\SiteBanners\Block;

use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Element\Template\Context;
use Vodacom\SiteBanners\Helper\HeavyBannerProcessor;

/**
 * Class BannerStats
 * Block that demonstrates Proxy pattern usage
 * 
 * KEY CONCEPT:
 * HeavyBannerProcessor is injected, but in di.xml we configure it as Proxy:
 * - WITHOUT Proxy: HeavyBannerProcessor instantiated NOW (expensive!)
 * - WITH Proxy: Proxy object created (cheap), real object created only when method called
 * 
 * EDUCATIONAL PURPOSE:
 * This block shows conditional usage of heavy dependency:
 * - If $showStats = false, HeavyBannerProcessor is NEVER instantiated
 * - If $showStats = true, instantiation happens only when getStatistics() is called
 * 
 * TESTING:
 * 1. Set $showStats = false, check logs: "HeavyBannerProcessor initialized" should NOT appear
 * 2. Set $showStats = true, check logs: "HeavyBannerProcessor initialized" appears
 * 
 * @package Vodacom\SiteBanners\Block
 */
class BannerStats extends Template
{
    /**
     * @var HeavyBannerProcessor
     * NOTE: In di.xml, we configure this as Proxy
     * 
     * Type hint is HeavyBannerProcessor, but Magento injects:
     * Vodacom\SiteBanners\Helper\HeavyBannerProcessor\Proxy
     * 
     * This Proxy class is auto-generated by Magento!
     */
    private HeavyBannerProcessor $heavyProcessor;

    /**
     * @var bool
     * Controls whether statistics are shown (and thus whether HeavyBannerProcessor is used)
     */
    private bool $showStats;

    /**
     * BannerStats constructor.
     * 
     * WITHOUT Proxy Configuration:
     * - HeavyBannerProcessor instantiated NOW
     * - Constructor runs: "HeavyBannerProcessor initialized" logged
     * - Cost: Expensive initialization even if never used
     * 
     * WITH Proxy Configuration (our approach in V5.0.2):
     * - Proxy object created (lightweight placeholder)
     * - Real HeavyBannerProcessor ONLY created when method is called
     * - Cost: Minimal until actually needed
     * 
     * @param Context $context
     * @param HeavyBannerProcessor $heavyProcessor
     * @param bool $showStats
     * @param array $data
     */
    public function __construct(
        Context $context,
        HeavyBannerProcessor $heavyProcessor,
        bool $showStats = false,
        array $data = []
    ) {
        parent::__construct($context, $data);
        $this->heavyProcessor = $heavyProcessor;
        $this->showStats = $showStats;
        
        // At this point:
        // - WITH Proxy: $heavyProcessor is Proxy object (not real class)
        // - Real HeavyBannerProcessor not instantiated yet
    }

    /**
     * Get banner statistics
     * 
     * LAZY LOADING DEMONSTRATION:
     * - If $showStats is false, this method is never called
     * - Thanks to Proxy, HeavyBannerProcessor is never instantiated!
     * - If $showStats is true, calling this triggers real instantiation
     * 
     * @return array
     */
    public function getStatistics(): array
    {
        if (!$this->showStats) {
            return [];
        }

        // CRITICAL MOMENT: This line triggers real HeavyBannerProcessor instantiation
        // Check var/log/system.log for "HeavyBannerProcessor initialized" message
        return $this->heavyProcessor->getStatistics();
    }

    /**
     * Get detailed analysis
     * 
     * Another method demonstrating Proxy behavior
     * 
     * @return array
     */
    public function getDetailedAnalysis(): array
    {
        if (!$this->showStats) {
            return [];
        }

        // If this is first method called, it triggers instantiation
        // If getStatistics() was called first, real object already exists
        return $this->heavyProcessor->getDetailedAnalysis();
    }

    /**
     * Should show stats
     * 
     * @return bool
     */
    public function shouldShowStats(): bool
    {
        return $this->showStats;
    }

    /**
     * Check if heavy processor would be used
     * 
     * Educational method to demonstrate Proxy transparency
     * 
     * @return string
     */
    public function getProxyInfo(): string
    {
        // This does NOT trigger instantiation (just checking instanceof)
        $className = get_class($this->heavyProcessor);
        
        if (strpos($className, 'Proxy') !== false) {
            return "✅ Using Proxy: {$className}";
        }
        
        return "❌ Direct injection (no Proxy): {$className}";
    }
}
