<?php
declare(strict_types=1);

namespace Vodacom\SiteBanners\Service;

use Vodacom\SiteBanners\Api\BannerRepositoryInterface;
use Vodacom\SiteBanners\Api\Data\BannerInterfaceFactory;
use Vodacom\SiteBanners\Model\ResourceModel\Banner\CollectionFactory;
use Magento\Framework\Api\SearchCriteriaBuilder;
use Magento\Framework\Exception\CouldNotSaveException;
use Magento\Framework\Exception\LocalizedException;
use Psr\Log\LoggerInterface;

/**
 * Class BannerService
 * Service layer demonstrating Factory and CollectionFactory patterns
 * 
 * KEY CONCEPTS DEMONSTRATED:
 * 1. BannerInterfaceFactory - Creates NEW Banner instances dynamically
 * 2. CollectionFactory - Creates FRESH Collection instances for independent queries
 * 3. Service Layer Pattern - Business logic separated from controllers/blocks
 * 
 * @package Vodacom\SiteBanners\Service
 */
class BannerService
{
    /**
     * @var BannerRepositoryInterface
     */
    private BannerRepositoryInterface $bannerRepository;

    /**
     * @var BannerInterfaceFactory
     * Factory for creating new Banner instances
     * NOTE: This class is auto-generated by Magento during setup:di:compile!
     * You never write BannerInterfaceFactory.php manually
     */
    private BannerInterfaceFactory $bannerFactory;

    /**
     * @var CollectionFactory
     * Factory for creating fresh Collection instances
     * NOTE: This class is also auto-generated!
     * Location: generated/code/Vodacom/SiteBanners/Model/ResourceModel/Banner/CollectionFactory.php
     */
    private CollectionFactory $collectionFactory;

    /**
     * @var SearchCriteriaBuilder
     */
    private SearchCriteriaBuilder $searchCriteriaBuilder;

    /**
     * @var LoggerInterface
     */
    private LoggerInterface $logger;

    /**
     * BannerService constructor.
     * 
     * Demonstrates Factory injection:
     * - BannerInterfaceFactory creates NEW banners (not singletons)
     * - CollectionFactory creates FRESH collections (clean slate each time)
     * 
     * @param BannerRepositoryInterface $bannerRepository
     * @param BannerInterfaceFactory $bannerFactory
     * @param CollectionFactory $collectionFactory
     * @param SearchCriteriaBuilder $searchCriteriaBuilder
     * @param LoggerInterface $logger
     */
    public function __construct(
        BannerRepositoryInterface $bannerRepository,
        BannerInterfaceFactory $bannerFactory,
        CollectionFactory $collectionFactory,
        SearchCriteriaBuilder $searchCriteriaBuilder,
        LoggerInterface $logger
    ) {
        $this->bannerRepository = $bannerRepository;
        $this->bannerFactory = $bannerFactory;
        $this->collectionFactory = $collectionFactory;
        $this->searchCriteriaBuilder = $searchCriteriaBuilder;
        $this->logger = $logger;
    }

    /**
     * Create a new banner programmatically
     * 
     * Use Case: API endpoints, import scripts, admin actions, console commands
     * Why Factory? We need a NEW instance each time, not a singleton
     * 
     * @param array $data
     * @return \Vodacom\SiteBanners\Api\Data\BannerInterface
     * @throws CouldNotSaveException
     */
    public function createBanner(array $data): \Vodacom\SiteBanners\Api\Data\BannerInterface
    {
        try {
            // Factory creates NEW Banner instance
            // Each call to create() returns a new object
            $banner = $this->bannerFactory->create();
            
            // Set data
            $banner->setTitle($data['title'] ?? 'Untitled Banner');
            $banner->setContent($data['content'] ?? '');
            $banner->setIsActive((bool)($data['is_active'] ?? 1));
            $banner->setSortOrder($data['sort_order'] ?? 0);
            $banner->setActiveFrom($data['active_from'] ?? null);
            $banner->setActiveTo($data['active_to'] ?? null);

            // Save via repository
            return $this->bannerRepository->save($banner);
        } catch (\Exception $e) {
            $this->logger->error('Error creating banner: ' . $e->getMessage());
            throw new CouldNotSaveException(__('Could not create banner: %1', $e->getMessage()));
        }
    }

    /**
     * Clone an existing banner
     * 
     * Use Case: Duplicate banner for A/B testing, create variations
     * Why Factory? Create NEW instance with copied data (not reference to original)
     * 
     * @param int $bannerId
     * @return \Vodacom\SiteBanners\Api\Data\BannerInterface
     * @throws LocalizedException
     */
    public function cloneBanner(int $bannerId): \Vodacom\SiteBanners\Api\Data\BannerInterface
    {
        try {
            // Get original banner
            $originalBanner = $this->bannerRepository->getById($bannerId);

            // Create NEW instance via Factory (not a reference!)
            $clonedBanner = $this->bannerFactory->create();

            // Copy data (but not ID - we want a NEW record)
            $clonedBanner->setTitle($originalBanner->getTitle() . ' (Copy)');
            $clonedBanner->setContent($originalBanner->getContent());
            $clonedBanner->setIsActive(false); // Inactive by default
            $clonedBanner->setSortOrder($originalBanner->getSortOrder() + 10);
            $clonedBanner->setActiveFrom($originalBanner->getActiveFrom());
            $clonedBanner->setActiveTo($originalBanner->getActiveTo());

            // Save
            return $this->bannerRepository->save($clonedBanner);
        } catch (\Exception $e) {
            $this->logger->error("Error cloning banner {$bannerId}: " . $e->getMessage());
            throw new LocalizedException(__('Could not clone banner: %1', $e->getMessage()));
        }
    }

    /**
     * Get banners by multiple sort orders
     * 
     * Use Case: Need separate collections for different queries
     * Why CollectionFactory? Each call needs FRESH collection (no filter pollution)
     * 
     * @param array $sortOrders
     * @return array
     */
    public function getBannersBySortOrders(array $sortOrders): array
    {
        $result = [];

        foreach ($sortOrders as $sortOrder) {
            // Create FRESH collection for each sort order
            // If we reused same collection, filters would accumulate!
            $collection = $this->collectionFactory->create();
            
            $collection->addFieldToFilter('sort_order', $sortOrder);
            $collection->addFieldToFilter('is_active', '1');

            $result[$sortOrder] = $collection->getItems();
        }

        return $result;
    }

    /**
     * Get banner statistics using multiple independent collections
     * 
     * Why CollectionFactory? Need independent collections for each stat
     * Each collection has different filters - can't reuse same instance
     * 
     * @return array
     */
    public function getBannerStatistics(): array
    {
        // Collection 1: Active banners
        $activeCollection = $this->collectionFactory->create();
        $activeCollection->addFieldToFilter('is_active', '1');
        $activeCount = $activeCollection->getSize();

        // Collection 2: Inactive banners (need fresh collection)
        $inactiveCollection = $this->collectionFactory->create();
        $inactiveCollection->addFieldToFilter('is_active', '0');
        $inactiveCount = $inactiveCollection->getSize();

        // Collection 3: Total banners
        $totalCollection = $this->collectionFactory->create();
        $totalCount = $totalCollection->getSize();

        return [
            'active' => $activeCount,
            'inactive' => $inactiveCount,
            'total' => $totalCount,
            'active_percentage' => $totalCount > 0 ? round(($activeCount / $totalCount) * 100, 2) : 0
        ];
    }

    /**
     * Bulk create banners
     * 
     * Use Case: Import from CSV, seed data, data migration
     * Why Factory? Create multiple NEW instances in loop
     * 
     * @param array $bannersData
     * @return array
     */
    public function bulkCreateBanners(array $bannersData): array
    {
        $results = [
            'success' => [],
            'failed' => []
        ];

        foreach ($bannersData as $bannerData) {
            try {
                // Factory creates NEW instance for each iteration
                // Without Factory, we'd be modifying the same object repeatedly!
                $banner = $this->bannerFactory->create();
                $banner->setData($bannerData);

                $savedBanner = $this->bannerRepository->save($banner);
                $results['success'][] = $savedBanner->getBannerId();
            } catch (\Exception $e) {
                $results['failed'][] = [
                    'data' => $bannerData,
                    'error' => $e->getMessage()
                ];
                $this->logger->error('Bulk create error: ' . $e->getMessage());
            }
        }

        return $results;
    }

    /**
     * Get active banners count
     * 
     * Simple example of CollectionFactory usage
     * 
     * @return int
     */
    public function getActiveBannersCount(): int
    {
        $collection = $this->collectionFactory->create();
        $collection->addFieldToFilter('is_active', '1');
        return $collection->getSize();
    }
}
